### ISSUE TITLE
[Project Announcement] Call for review

### ISSUE THREAD

**Issue by hwangdeokThien** [Deadinside-at-HCMUS/CSC17104-project#8]
Hello everyone, our team's project has been completed. You can review it and provide feedback by creating new issues. The team will review and consider any necessary corrections. Thank you all.

**Comment by Tointech** [comment]
We are happy to hear your comments and look forward to receiving your feedback on our team's project 😃

**Comment by khiemnguyen812** [comment]
- File README.md hơi sơ sài.
- Hướng trả lời câu hỏi hợp lý, sử dụng biểu đồ dễ nhìn, dễ hiểu.
- Sai tên ở biểu đồ Heart disease by gender.
- Thiếu ảnh planning.

**Comment by LuisNguyenThenh** [comment]
Good repo, highly recommend to read.

**Comment by mquaan** [comment]
_- The visualization is very nice, but it would be better if there was one more question._

**Comment by Tointech** [comment]
> * File README.md hơi sơ sài.
> * Hướng trả lời câu hỏi hợp lý, sử dụng biểu đồ dễ nhìn, dễ hiểu.
> * Sai tên ở biểu đồ Heart disease by gender.
> * Thiếu ảnh planning.

**Comment by Tointech** [comment]
> * File README.md hơi sơ sài.
> * Hướng trả lời câu hỏi hợp lý, sử dụng biểu đồ dễ nhìn, dễ hiểu.
> * Sai tên ở biểu đồ Heart disease by gender.
> * Thiếu ảnh planning.

We have updated based on your feedback, thank you for your contribution
